### ISSUE TITLE
Match the set of buttons provided OOTB with CKEditor v4 in the Backdrop core "Filtered HTML" format

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/ckeditor5#13]
This is the set of buttons added by default when selecting CKEditor 5 as the editor for a newly-created text format:
<img width="666" alt="image" src="https://github.com/quicksketch/ckeditor5/assets/2423362/3d6d0a23-7ca3-4aba-8672-d95d7ab6cb86">

And this is the set of buttons that we have enabled for the "Filtered HTML" text format:
<img width="633" alt="image" src="https://github.com/quicksketch/ckeditor5/assets/2423362/cd28f7bb-3758-4b07-a3e8-1cd88c8ddde1">

I'm fine with the addition of the "remove formatting" button to the defaults in CKE5, since that seems to be commonly-used 👍🏼 ...not sure about its position though - it doesn't feel that it belongs together with the "Source" button 🤔 

We should also add the link/unlink buttons in the enabled-by-default set for CKE5, in the same/respective position as in CKE4.

While at it, perhaps also move the undo/redo buttons in the respective position in the list of available buttons?

**Comment by quicksketch** [comment]
Good suggestions and thanks for the 1-to-1 screenshots for comparison. On a related notes, there are a few buttons that don't have CKEditor 5 versions, including:

* Copy
* Paste
* Paste from Word
* Show invisibles
* Maximize

Also, there's no specific "Unlink" button (it's built into the Balloon UI when a link is selected in the editor).

It looks like in both CKEditor 4 and 5, the order of disabled buttons is determine purely by the order the plugins are defined, which might not be great but it's also not much of a problem. The order of disabled buttons seems largely unintentional.

**Comment by quicksketch** [comment]
I ran across a core bug that is causing the link button to show as disabled even after saving with it enabled. This also is affecting the configuration of new text formats. The link button should be enabled, but it's getting disabled by the filtering system. I've set up CKEditor 5 to handle passing specific attributes on tags, while CKEditor 4 only dealt with passing HTML tags. The problem seems to be that specifying the `id` attribute is causing a conflict with core's handling of forbidding `on*` attributes. Not specifying the `id` attribute as required allows the button to stay enabled.

I merged https://github.com/quicksketch/ckeditor5/pull/27 that makes progress on this issue. It moves undo/redo to the end of the disabled buttons and temporarily fixes the link button from getting disabled. Seems like maybe we should reconsider the default buttons, even though right now it's one-to-one as much as possible, I'm not sure the new button arrangement makes sense with Link and Image grouped.

Just for a quick reference, here's what the Google Docs toolbar looks like currently:

![image](https://github.com/quicksketch/ckeditor5/assets/100206/993a07fe-4c03-48ca-b2fc-ceaf8868f355)

Though Google Docs' intention is pretty different from our (imitating a traditional for-print word processor vs fitting into a website's content model), a few things are surprisingly similar, like grouping link and image; and putting remove-formatting at the end (or near it) of the toolbar.

CKEditor 5 also provides the option to [consolidate the align options into a single button with a drop-down](https://ckeditor.com/docs/ckeditor5/latest/features/text-alignment.html). I'm not sure if that is something we should utilize by default (it's already a button option) and thoughts are appreciated.

**Comment by klonos** [comment]
Thanks @quicksketch 🙏🏼 

Here's the current state:
![image](https://github.com/quicksketch/ckeditor5/assets/2423362/3bb0d791-1744-40ec-9337-7c8db452bf11)
- The major thing was the link button, which is now added in the default set of active buttons OOTB 👍🏼  (albeit with a workaround at the moment that doesn't pass the `id` attribute)
- I am ambivalent re the order of the "Code block" button. From a use/functionality point of view, I'd put it next to the "Code" button, however, the code button formats words/lines of text, so I see the logic in it being grouped along with the underline/strikethrough/subscript/superscript buttons vs "Code block" being grouped along with other buttons that add "block" elements, such as the table button. So I think we're good here 👍🏼 
- The labels for both the "Code" and "Code block" buttons are `Code` though, which we should fix.
- And finally, yeah, I also think that we shouldn't be grouping the alignment buttons into a single button.

**Comment by quicksketch** [comment]
> The major thing was the link button, which is now added in the default set of active buttons OOTB 👍🏼 (albeit with a workaround at the moment that doesn't pass the id attribute)

This has now been fixed I believe. ID, title, class, etc all now work on links.

> The labels for both the "Code" and "Code block" buttons are Code though, which we should fix.

PR filed at https://github.com/backdrop-contrib/ckeditor5/pull/72

It sounds like all other requests have been met here, so after merging #72 we should be able to close this.
