### ISSUE TITLE
Disable rather than hide editor settings (Headings, Style List) that have button dependencies

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/ckeditor5#14]
This works as expected with CKE4 (although these are fieldsets instead of vtabs), but with CKE5 these vertical tabs are always visible - even when the required buttons have not been added to the active toolbar.

Since these settings have been moved from fieldsets to vtabs, there is no issue with the vertical space and scrolling in this form (which can be a UX concern). So perhaps instead of hiding the vertical tabs completely while the required buttons aren't available, we could replace the set of settings included in them with a help text that says "Settings for this feature will become available when the XYZ button has been added to the active toolbar". I believe that this will help with the discoverability of these features as well.

**Comment by quicksketch** [comment]
I agree with your thinking, that showing the vertical tab all the time but describing why it's not enabled would probably be better than hiding the tab altogether.

That said, the vertical tabs _do_ actually hide and show right now based on the buttons enable. Perhaps there's a particular set of steps which breaks this functionality, but they should behave this way. Here's a screen recording:

![Peek 2023-06-25 22-19](https://github.com/quicksketch/ckeditor5/assets/100206/881ce859-c1df-4514-a725-09f13acb9aa1)

Though there's a bit of display issue when _all_ buttons that have settings are disabled, it leaves an empty gray border that looks like a line. But rather than fix the display issue, I think your suggestion is better: show but disable the options with an explanation.

**Comment by klonos** [comment]
> Perhaps there's a particular set of steps which breaks this functionality

There is. It seems to be happening when creating a new format - not when editing existing ones. So:
- head over to `admin/config/content/formats/add`
- select "CKEditor 5" from the "Text editor" select
- notice how the the vtab for "Style list" is present, despite the respective button not being in the active toolbar 👎🏼 
- move the "Styles" button to the active toolbar -> the "Style list" vtab remains 👍🏼 
- move the "Styles" button to the available/disabled toolbar  -> the "Style list" vtab remains 👎🏼 
- move any of the "Link"/"Image"/"Headings" buttons to the available/disabled toolbar  -> the respective vtabs remain 👎🏼

The above works as expected on existing text formats.

**Comment by quicksketch** [comment]
I'm looking into this issue of the vertical tabs not hiding when adding a new text format, but it's not yet clear why this is happening.

**Comment by quicksketch** [comment]
@klonos for now I fixed the issue where settings were not properly hiding when their dependency buttons were missing. We could reopen this issue or open a new one for improving the display of these options.
