### ISSUE TITLE
Consider adding support for @-mentions to existing user accounts on the site.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/ckeditor5#20]
https://ckeditor.com/docs/ckeditor5/latest/features/mentions.html

**Comment by quicksketch** [comment]
I'm tempted to say this should be a contrib module feature, rather than a part of the core build. Plugins can be loaded by separate modules, and mentions might require some specific configuration (like which users can actually be referenced). The CKEditor core implementation also seems to expect a pre-defined list of user names. To show all user names on Backdrop site would probably required customizing CKEditor via an additional add-on plugin that customizes the Mentions plugin to add usernames via an AJAX autocomplete. Seems like a big undertaking for what might not be commonly used.

**Comment by klonos** [comment]
> The CKEditor core implementation also seems to expect a pre-defined list of user names.

Yeah, I was thinking that in our case we'd use some callback to populate that list, respecting the permissions by the currently logged-in user re viewing other people's user accounts.

I see how this feature would be useful in blog/community sites, but I also appreciate that it shouldn't be on by default. The core "View user profiles" permission should be respected.

**Comment by herbdool** [comment]
Yeah, this is contrib material.

**Comment by quicksketch** [comment]
I'm going to go ahead and close this issue. It would still be neat but I don't think it's a focus for this module directly.
